src/twweb/views/task.py
# Copyright (C) 2018 Michał Góral.
#
# This file is part of TWWeb
#
# TWWeb is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# TWWeb is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with TWWeb. If not, see <http://www.gnu.org/licenses/>.

from collections import OrderedDict

from flask import current_app as app
from flask import (Blueprint, render_template, request, redirect,
                   url_for, flash, Markup, session)
from flask_login import login_required, login_user, logout_user, current_user
from flask_wtf.csrf import CSRFError
from wtforms.validators import InputRequired, AnyOf
from taskw.exceptions import TaskwarriorError

from twweb.forms import (TaskForm, TaskActionForm, LoginForm, RegistrationForm,
                         ActionForm)
from twweb.validators import Forbidden
from twweb.model import db, User, login_manager

from .view_utils import (no_cache, session_save_form, session_load_form,
                          session_clear_form, twweb_template)

task_view = Blueprint('task', __name__)

class TaskGroup:
    def __init__(self):
        self.pending = []
        self.waiting = []
        self.completed = []
        self.other = []

    def __len__(self):
        return len(self.pending)


def form_errors(form):
    for e in form.errors:
        yield '%s: %s' % (e.capitalize(), '\n'.join(form.errors[e]))


def stringify_filter(flt, *, init=None):
    s = init if init else ''
    multi_keys = app.config['TW_KEYS_HAS_CHECK']

    for key, value in flt.items():
        if key in multi_keys:
            for elem in value.split(','):
                s += ' %s.has:%s' % (key, elem.strip())
        else:
            s += ' %s:%s' % (key, value)
    s = s.strip()

    if s:
        return '( %s )' % s
    return ''


def sort(tasks, key, order_name='asc'):
    def _get(key, default=None):
        def _f(dct):
            return dct.get(key, default)
        return _f

    rev = (order_name == 'desc')
    tasks.sort(key=_get(key, ''), reverse=rev)


def limit(tasks, no):
    tasks[:] = tasks[:no]


def postprocess(tasks, actions):
    if 'sort' in actions:
        sort(tasks, actions['sort'], actions.get('ord', 'desc'))
    if 'limit' in actions:
        limit(tasks, int(actions['limit']))


def split_filters():
    actions_names = ('sort', 'ord', 'view', 'limit')
    args = request.args.copy()

    actions = {}

    for an in actions_names:
        if an in args:
            actions[an] = args[an]
            del args[an]

    return args, actions


def uuids(id_list):
    if not id_list:
        return []
    query = ','.join(str(id_) for id_ in id_list if id_ > 0)
    tasks = app.tw._get_task_objects(query , 'export')
    return [t['uuid'] for t in tasks]


def ids(uuid_list):
    if not uuid_list:
        return []
    query = ' or '.join(str('uuid:%s' % u) for u in uuid_list)
    tasks = app.tw._get_task_objects(query , 'export')
    return [t['id'] for t in tasks if t['id']]


def change_task_status(task, status):
    def _completed(task, _):
        app.tw.task_done(uuid=task['uuid'])

    def _delete(task, _):
        app.tw.task_delete(uuid=task['uuid'])

    def _other(task, status):
        task['status'] = status.strip()
        app.tw.task_update(task)

    routines = {'completed': _completed, 'delete': _delete}
    changer = routines.get(status, _other)

    if not task:
        flash('Task doesn\'t exist.', 'error')
        return False

    try:
        changer(task, status)
    except TaskwarriorError as e:
        flash(e.stderr.decode('utf-8'), 'error')
        return False
    except ValueError as e:
        flash(str(e), 'error')
        return False

    return True


def add_get(form):
    session_load_form(form)
    return twweb_template('edit.html', form=form, title='New Task')


def add_post(form):
    form.uuid.validators.insert(0, Forbidden())
    form.description.validators.insert(0, InputRequired())

    session_save_form(form)

    if form.validate():
        discard_fields = ('csrf_token')
        data = form.data
        dct = {name: data[name]
               for name in data
               if name not in discard_fields and data[name]}

        # Due to usability reasons, user is required to provide task ids.
        # Furthermore, only task with ids (i.e. pending ones) can actually block
        # any task, so it makes more sense than providing anything else. But TW
        # requires uuids here, so here we are.
        if 'depends' in dct:
            dct['depends'] = uuids(dct['depends'])

        task = app.tw.task_add(**dct)
        msg = 'Created a new task: <a href="%s">%d</a>' % \
            (url_for('task.task', uuid=task['uuid']), task['id'])
        messages = [('success', Markup(msg))]
        session_clear_form(form)

        form.description.data = ''
    else:
        messages = [('error', e) for e in form_errors(form)]

    return twweb_template('edit.html', messages=messages, form=form,
                          title="New Task")


@task_view.route('/add', methods=['GET', 'POST'])
@login_required
@no_cache
def add():
    form = TaskForm(request.form)
    f = globals()['add_%s' % request.method.lower()]
    return f(form)


def edit_post(uuid):
    task = app.tw.get_task(uuid=uuid)[1]
    messages = []

    form = TaskForm()

    form.uuid.validators.insert(0, Forbidden())
    form.description.validators.insert(0, InputRequired())

    if form.validate():
        # Most of these fields don't exist in form, but maybe in future some of
        # them will (as e.g. hidden input)
        discard_fields = ('csrf_token', 'next', 'id', 'uuid', 'modified',
                          'entry')
        data = form.data
        dct = {name: data[name]
               for name in data
               if name not in discard_fields}

        if 'depends' in dct:
            dct['depends'] = uuids(dct['depends'])

        # update dict, task is saved below
        task.update(dct)

        try:
            up = app.tw.task_update(task)[1]
        except TaskwarriorError as e:
            messages.append(('error', e.stderr.decode('utf-8')))
        else:
            msg = 'Task <a href="%s">%d</a> successfully updated.' % \
                (url_for('task.task', uuid=up['uuid']), up['id'])
            flash(Markup(msg), 'success')
            return form.redirect()

    for e in form_errors(form):
        messages.append(('error', e))

    return twweb_template('edit.html', form=form, title='Edit Task',
                          messages=messages)


def edit_get(uuid):
    task = app.tw.get_task(uuid=uuid)[1]
    if not task:
        flash('Requested task does not exist.', 'error')
        return redirect(url_for('task.add'), code=302)

    if 'depends' in task:
        task['depends'] = ids(task['depends'])

    form = TaskForm(None, data=task, next=request.referrer)
    return twweb_template('edit.html', form=form, task=task,
                          title='Edit Task')


@task_view.route('/edit/<uuid>', methods=['GET', 'POST'])
@login_required
@no_cache
def edit(uuid):
    f = globals()['edit_%s' % request.method.lower()]
    return f(uuid)


@task_view.route('/complete', methods=['POST'],
                 defaults={'status': 'completed'},
                 endpoint='complete')
@task_view.route('/delete', methods=['POST'],
                 defaults={'status': 'deleted'},
                 endpoint='delete')
@task_view.route('/change_status', methods=['POST'], defaults={'status': None})
@login_required
def change_status(status):
    '''A common method of changing task status. User can mark task as completed
    and deleted. Generic `change_status` route exists for undoing purposes.'''
    form = TaskActionForm()

    if status is None:
        form.param.validators = [InputRequired(),
                                 AnyOf(['pending', 'deleted', 'completed',
                                        'waiting', 'recurring'])]
        status = form.param.data
    else:
        # For /complete and /delete routes only one status value is allowed, so
        # we'll block setting it via a param field.
        form.param.validators = [Forbidden()]

    if form.validate():
        task = app.tw.get_task(uuid=form.uuid.data)[1]
        if not task:
            flash('Incorrect UUID: %s' % form.uuid.data, 'error')
        else:
            prev_status = task['status']
            if change_task_status(task, status):
                red = form.next.data or url_for('task.task', uuid=task['uuid'])
                rendered_form = TaskActionForm(
                    formdata=None,
                    uuid=str(task['uuid']),
                    param=prev_status,
                    next=red)

                undo_html = render_template(
                    'form-action.html',
                    action='task.change_status',
                    label='Undo',
                    text='Task changed to %s.' % status,
                    form=rendered_form)
                flash(Markup(undo_html), 'success')
    else:
        for e in form_errors(form):
            flash(e, 'error')

    return form.redirect()


@task_view.route('/annotate', methods=['POST'])
@login_required
def annotate():
    form = TaskActionForm()
    form.param.validators = [InputRequired()]
    if form.validate():
        task = app.tw.get_task(uuid=form.uuid.data)[1]
        if not task:
            flash('Incorrect UUID: %s' % form.uuid.data, 'error')
        else:
            ann = form.param.data.strip()
            try:
                app.tw.task_annotate(task, ann)

src/twweb/templates/accordion.html
{% extends "layout.html" %}

{% import 'macros.html' as macros %}

{% macro task_group(group, name) %}

{% if group[name]|length > 0 %}
<h4>{{ name|capitalize }}</h4>
<div class="list-group mb-2">

    {% for task in group[name] %}
    <div class="list-group-item list-group-item-action">
    <div class="d-flex justify-content-between">
        <div>{{ task.description|urlize }}</div>
        <div class="dropdown">
            <button class="btn btn-outline-secondary btn-no-border btn-sm dropdown-toggle caret-off" type="button" data-boundary="viewport" data-toggle="dropdown" title="Task actions" aria-label="Task actions" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-h" aria-hidden="true"></i>
            </button>

            {{ macros.task_actions(task) }}
        </div>
    </div>
        {% if task.annotations %}
        <ul class="list-unstyled ml-4">
            {% for ann in task.annotations %}
            <li><small>
                <span class="text-muted">{{ ann.entry.strftime('%Y-%m-%d') }}:</span> {{ ann|urlize }}
            </small></li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
    {% endfor %}

</div>
{% endif %}

{% endmacro %}

{% macro badge(group, name, color) %}
{% set l = group[name]|length %}
{% if l > 0 %}
<span class="ml-1 badge badge-{{ color }}" title="{{ l }} {{ name }}" aria-label="{{ l }} {{ name }}">{{ l }}</span>{% endif %}
{% endmacro %}

{% block content %}
<div id="accordion" role="tablist">

    {% for name in groups  %}
    {% set group = groups[name] %}
    <div class="card">
        <a data-toggle="collapse" href="#coll-{{ loop.index0 }}" role="button" aria-expanded="false" aria-controls="coll-{{ loop.index0 }}">
            <div class="card-header" role="tab" id="heading-{{ loop.index0 }}">
                <h5 class="mb-0 d-flex justify-content-between">
                    {{ name }}
                    <span>
                    {{ badge(group, 'pending', 'primary') }}{{ badge(group, 'waiting', 'secondary') }}{{ badge(group, 'completed', 'success') }}{{ badge(group, 'other', 'info') }}
                    </span>
                </h5>
            </div>
        </a>

        <div id="coll-{{ loop.index0 }}" class="collapse" role="tabpanel" aria-labelledby="heading-{{ loop.index0 }}" data-parent="#accordion">
            <div class="card-body">
                {{ task_group(group, 'pending') }}
                {{ task_group(group, 'waiting') }}
                {{ task_group(group, 'completed') }}
                {{ task_group(group, 'other') }}
            </div>
        </div>
    </div>
    {% endfor %}

    {{ macros.annotate_modal() }}
</div>
{% endblock content %}

src/twweb/templates/cards.html
{% extends "layout.html" %}

{% import 'macros.html' as macros %}

{% block content %}
    <!-- Controls row -->
    <div class="row">
        <div class="col-md-2 pb-4">
            <div class="dropdown">
                <button class="btn btn-primary dropdown-toggle btn-block" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" id="sort-button">Sort by{% if request.args.sort %} {{ request.args.sort | lower }}{% endif %}</button>
                <div class="dropdown-menu" aria-labelledby="sort-button">
                    <a class="dropdown-item" href="{{ query(sort='urgency', ord='desc') }}">Urgency</a>
                    <a class="dropdown-item" href="{{ query(sort='priority', ord='desc') }}">Priority</a>
                    <a class="dropdown-item" href="{{ query(sort='project', ord='desc') }}">Project</a>
                    <a class="dropdown-item" href="{{ query(sort='status', ord='desc') }}">Status</a>
                    <a class="dropdown-item" href="{{ query(sort='entry', ord='desc') }}">Entry Date</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{{ query(sort=None, ord=None) }}"><i class="fas fa-eraser" aria-hidden="true"></i> Clear</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{{ query(ord='desc') }}"><i class="fas fa-sort-amount-down" aria-hidden="true"></i> Highest first</a>
                    <a class="dropdown-item" href="{{ query(ord='asc') }}"><i class="fas fa-sort-amount-up" aria-hidden="true"></i> Lowest first</a>
                </div>
            </div>
        </div>
        <div class="col-md-10 pb-4">
            <form action="{{url_for('task.tasks')}}" method="get">
                <div class="input-group">
                    <input class="form-control" type="text" name="filter" placeholder="Custom filter" aria-label="Custom filter"{%with f=query_values('filter')%}{%if f%}value="{{f[0]|e}}"{%endif%}{%endwith%} />
                    <div class="input-group-append">
                        <button class="btn btn-success" type="submit" aria-label="Use custom filter">
                            <i class="fas fa-filter" aria-hidden="true"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    {{ macros.task_heading('cards', tasks) }}

    <!-- Tasks -->
    {% for task_row in tasks | batch(3) %}
    <div class="row">
        {% for task in task_row  %}
        <div class="col-md-4 pb-4 task-{{task.id}}">
            <div class="card h-100 {% if task.priority == 'H' and task.status == 'pending' %} border-danger{% endif %}">
                <div class="card-body text-center">
                    <p class="card-text{% if task.status != 'pending' %} text-secondary{% elif task.priority == 'H' %} text-danger{% endif %}">{{ task.description|urlize }}</p>
                </div>

                <div class="card-footer">
                    <ul class="list-unstyled card-text small text-right">
                        <li class="text-muted">
                            <ul class="list-inline">
                                {% if task.annotations %}<li class="list-inline-item"><i class="fas fa-comments" title="Annotations exist" aria-hidden="true"></i><span class="sr-only">Annotations exist</span></li>{% endif %}
                                {% if task.project %}<li class="list-inline-item"><i class="fas fa-folder" aria-hidden="true"></i><span class="sr-only">Project</span> <a class="text-info" href="{{ query(project=task.project) }}">{{ task.project }}</a></li>{% endif %}
                                {% if task.tags %}<li class="list-inline-item"><i class="fas fa-tags" aria-hidden="true"></i><span class="sr-only">Tags</span>{% for tag in task.tags %} <a class="text-info" href="{{query(tags=tag)}}">{{tag}}</a>{% endfor %}</li>{% endif %}
                                <li class="list-inline-item dropdown">
                                    <button class="btn btn-outline-secondary btn-no-border btn-sm dropdown-toggle caret-off" type="button" data-boundary="viewport" data-toggle="dropdown" title="Task actions" aria-label="Task actions" aria-haspopup="true" aria-expanded="false">
                                        <i class="fas fa-ellipsis-h" aria-hidden="true"></i>
                                    </button>

                                    {{ macros.task_actions(task) }}
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
    {{ macros.annotate_modal() }}
{% endblock content %}

src/twweb/templates/edit.html
{% extends "layout.html" %}

{% import 'macros.html' as macros %}

{% macro form_field(field, placeholder=None, width='auto') %}
    {% set addon_id = "addon-" ~ field.id %}
    {% set attribs = {
        "class": "form-control",
        "placeholder": placeholder if placeholder else field.description,
        "aria-label": field.description,
        "aria-describedby": addon_id,
    } %}

    <div class="col-md-{{ width }}">
        <div class="input-group mb-3">
            <span class="input-group-prepend input-group-text" id="{{ addon_id }}">{{field.name|capitalize}}</span>
            {{ field(**attribs)|safe }}
        </div>
    </div>
{% endmacro %}

{% block heading %}
    <div class="row d-flex">
        <div class="mr-auto p-2">
            <h4>{{ page.title }}</h4>
        </div>

        {% if task %}
        <div class="p-2">
            {{ macros.btn_delete(task) }}
            {{ macros.btn_annotate(task) }}
            {{ macros.btn_done(task) }}
        </div>
        {% endif %}

        {% if task %}{{ macros.annotate_modal(task) }}{% endif %}
        {% if task %}{{ macros.form_done(task) }}{% endif %}
        {% if task %}{{ macros.form_delete(task) }}{% endif %}

    </div>
{% endblock heading %}

{% block content %}
    <form id="edit" action="{{request.path}}" method="post" class="pb-4">
        {{ form.hidden_tag() }}

        <div class="form-row">
            {{ form_field(form.description, "Task description", 12) }}
        </div>

        <div class="form-row">
            {{ form_field(form.tags, "comma, separated, tags", 4) }}
            {{ form_field(form.project, "project name", 3) }}
            {{ form_field(form.priority, width=2) }}
            {{ form_field(form.depends, '1, 2, 11', 3) }}
        </div>

        <div class="form-row">
            {{ form_field(form.due) }}
            {{ form_field(form.wait) }}
        </div>

        <button type="submit" class="btn btn-success">Save</button>
    </form>
{% endblock content %}

src/twweb/templates/error.html
{% extends "layout.html" %}

{% block content %}
<div class="row pb-4 pt-2">
    <div class="col">
        {{ error }}
    </div>
</div>

<div class="row">
    <div class="col">
        <button type="button" class="btn btn-primary" onclick="history.back();">Go back</button>
    </div>
</div>

</div></div>
{% endblock content %}

{% block footer %}{% endblock footer %}

src/twweb/templates/form-action.html
{% set label = label or action|capitalize %}
<form action="{{ url_for(action) }}" method="post">
    <div>
        {{ text }}
        {{ form.hidden_tag() }}
        <button type="submit" class="btn btn-link btn-sm alert-link" >{{ label }}</button>
    </div>
</form>

src/twweb/templates/macros.html
<!-- Annotate modal + toggle button -->
{% macro annotate_modal(task=None) %}
<div id="annotate-modal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">New annotation</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">&times;</button>
            </div>

            <div class="modal-body">
                <form id="annotate-form" action="{{ url_for('task.annotate') }}" method="post">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                    <input type="hidden" name="uuid" value="{%if task %}{{task.uuid}}{% endif %}" />
                    <input type="hidden" name="next" value="{{request.url}}" />
                    <input type="text" name="param" placeholder="Annotation" class="form-control">
                </form>
            </div>

            <div class="modal-footer">
                <button type="submit" class="btn btn-success" form="annotate-form">Annotate</button>
            </div>
        </div>
    </div>
</div>
{% endmacro %}

{% macro btn_annotate(task, class="btn-primary", text="Annotate") %}
<button type="button" class="btn {{ class }}" data-toggle="modal" data-target="#annotate-modal" data-uuid="{{ task.uuid }}">{{ text }}</button>
{% endmacro %}

<!-- Mark as done hidden form + a separate submit button -->
{% macro form_done(task) %}
{% if task.status not in ['deleted', 'completed'] %}
<form id="mark-done" action="{{ url_for('task.complete') }}" method="post">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    <input type="hidden" name="uuid" value="{{task.uuid}}" />
    <input type="hidden" name="next" value="{{request.url}}" />
</form>
{% endif %}
{% endmacro %}

{% macro btn_done(task) %}
<button type="submit" class="btn btn-success"{% if task.status not in ['deleted', 'completed'] %} form="mark-done"{% else %} disabled{% endif %}>Finish</button>
{% endmacro %}

<!-- Delete task hidden form + a separate submit button -->
{% macro form_delete(task) %}
{% if task.status in ['pending'] %}
<form id="mark-deleted" action="{{ url_for('task.delete') }}" method="post">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    <input type="hidden" name="uuid" value="{{task.uuid}}" />
    <input type="hidden" name="next" value="{{request.url}}" />
</form>
{% endif %}
{% endmacro %}

{% macro btn_delete(task) %}
<button type="submit" class="btn btn-warning" {% if task.status in ['pending'] %} form="mark-deleted"{% else %} disabled{% endif %}>Delete</button>
{% endmacro %}

<!-- Task display inside a table -->

{% macro trow(label, field, link=False) %}
<tr>
    <td>{{ label }}</td>
    {% if field or field == 0 %}
        {% if link %}
        <td><a href="{{ link }}">{{ field }}</a</td>
        {% else %}
        <td>{{ field }}</td>
        {% endif %}
    {% else %}
        <td>-</td>
    {% endif %}
</tr>
{% endmacro %}


<!-- Task list heading -->
{% macro task_heading(current, tasks) %}
<div class="row">
    <div class="container-fluid d-flex">
        <div>
            <h4>{{ tasks|length }} tasks</h4>
        </div>
        <div class="ml-auto">
        <nav class="nav">
        {% for name, href, icon in [('cards', query(view='cards'), 'fa-th'),
                                    ('table', query(view='table'), 'fa-th-list')] %}
                {% set label = name|capitalize + ' view' %}
                {% set hl = current == name %}
                {% if hl %}
                <a href="#" class="nav-link active" title="{{ label }}" aria-label="{{ label }}" aria-pressed="true">
                {% else %}
                <a href="{{ href }}" class="nav-link text-secondary" title="{{ label }}" aria-label="{{ label }}">
                {% endif %}
                    <i class="fas {{ icon }}"></i>
                </a>
        {% endfor %}
        </nav>
        </div>
    </div>
</div>
{% endmacro %}


<!-- Dropdown menu for task actions -->
{% macro task_actions(task) %}
<div class="dropdown-menu">
    {% if task.status not in ['deleted', 'completed'] %}
    <form action="{{ url_for('task.complete') }}" method="post" id="complete-{{ task.id }}">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <input type="hidden" name="uuid" value="{{task.uuid}}">
        <input type="hidden" name="next" value="{{request.url}}">
    </form>
    <form action="{{ url_for('task.delete') }}" method="post" id="delete-{{ task.id }}">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <input type="hidden" name="uuid" value="{{task.uuid}}">
        <input type="hidden" name="next" value="{{request.url}}">
    </form>

    <button type="submit" class="btn btn-sm btn-link dropdown-item" role="link" title="Complete task" aria-label="Complete task" form="complete-{{ task.id }}">
        <i class="fas fa-check" aria-hidden="true"></i> Complete
    </button>

    <button type="submit" class="btn btn-sm btn-link dropdown-item" role="link" title="Delete task" aria-label="Delete task" form="delete-{{ task.id }}">
        <i class="fas fa-trash" aria-hidden="true"></i> Delete
    </button>

    <div class="dropdown-divider"></div>
    {% endif %}

    <a href="{{ url_for('task.edit', uuid=task.uuid) }}" class="btn btn-sm dropdown-item" title="Edit task" aria-label="Edit task">
        <i class="fas fa-edit" aria-hidden="true"></i> Edit
    </a>

    <button type="button" class="btn btn-sm btn-link dropdown-item" data-uuid="{{ task.uuid }}" data-toggle="modal" data-target="#annotate-modal" title="Annotate task" aria-label="Annotate task">
        <i class="fas fa-comment" aria-hidden="true"></i> Annotate
    </button>

    <div class="dropdown-divider"></div>

    <a href="{{ url_for('task.task', uuid=task.uuid) }}" class="btn btn-sm dropdown-item" data-target="#details-{{task.uuid}}" title="Task details" aria-label="Task details">
        <i class="fas fa-info-circle" aria-hidden="true"></i> Details
    </a>
</div>
{% endmacro %}

src/twweb/templates/task.html
{% extends "layout.html" %}

{% import 'macros.html' as macros %}

{% block heading %}
    <div class="row d-flex">
        <div class="mr-auto p-2">
            <h4>{{ page.title }}</h4>
        </div>
        <div class="p-2">
            <a href="{{url_for('task.edit', uuid=task.uuid)}}" role="button" class="btn btn-primary">Edit</a>
        </div>
    </div>
{% endblock heading %}

{% block content %}
    {% if task %}
    <div class="row">
        <div class="col pb-2">
            <table class="table table-hover">
                <tbody>
                    {{ macros.trow("Description", task.description|urlize) }}

                    <tr>
                        <td>Annotations</td>
                        {% if task.annotations %}
                        <td>
                            <ul class="list-unstyled">
                            {% for ann in task.annotations %}
                            <li><em class="text-muted">{{ ann.entry.strftime('%Y-%m-%d %H:%M:%S') }}:</em> {{ ann|urlize }} </li>
                            {% endfor %}
                            </ul>
                        </td>
                        {% else %}
                        <td>-</td>
                        {% endif %}
                    </tr>

                    {{ macros.trow("Status", task.status|capitalize, url_for('task.tasks', status=task.status)) }}

                    {{ macros.trow("Project", task.project, url_for('task.tasks', project=task.project)) }}

                    <tr>
                        <td>Tags</td>
                        {% if task.tags %}
                        <td>{% for tag in task.tags %}<a href="{{url_for('task.tasks', tags=tag)}}">{{tag}}</a>{% if not loop.last %}, {% endif %}{% endfor %}</td>
                        {% else %}
                        <td>-</td>
                        {% endif %}
                    </tr>

                    {{ macros.trow("Priority", task.priority, url_for('task.tasks', priority=task.priority)) }}
                    {{ macros.trow("Urgency", task.urgency|int) }}

                    <tr>
                        <td>Depends on</td>
                        {% if task.depends %}
                        <td>{% for dep in task.depends %}<a href="{{ url_for('task.task', uuid=dep) }}" title="{{ get_task(uuid=dep).description }}">{{ dep }}</a>{% if not loop.last %}, {% endif %}{% endfor %}</td>
                        {% else %}
                        <td>-</td>
                        {% endif %}
                    </tr>

                    {% if task.due %}{{ macros.trow("Due date", task.due.strftime('%Y-%m-%d %H:%M:%S')) }}{% endif %}
                    {% if task.scheduled %}{{ macros.trow("Scheduled on", task.scheduled.strftime('%Y-%m-%d %H:%M:%S')) }}{% endif %}
                    {% if task.wait %}{{ macros.trow("Waits until", task.wait.strftime('%Y-%m-%d %H:%M:%S')) }}{% endif %}
                    {% if task.start %}{{ macros.trow("Started", task.start.strftime('%Y-%m-%d %H:%M:%S')) }}{% endif %}
                    {% if task.end %}{{ macros.trow("Ended", task.end.strftime('%Y-%m-%d %H:%M:%S')) }}{% endif %}

                    {{ macros.trow("Recurs until", task.until) }}
                    {{ macros.trow("Frequency", task.recur) }}
                    {{ macros.trow("Parent", task.parent, url_for('task.task', uuid=task.parent)) }}

                    {% for uda in udas %}
                    {{ macros.trow(uda|capitalize, task[uda]) }}
                    {% endfor %}

                    {{ macros.trow("UUID", task.uuid) }}
                    {{ macros.trow("ID", task.id) }}


                    {{ macros.trow("Entry", task.entry.strftime('%Y-%m-%d %H:%M:%S')) }}
                    {{ macros.trow("Last modification", task.modified.strftime('%Y-%m-%d %H:%M:%S')) }}

                </tbody>
            </table>
        </div>
    </div>
    {% endif %}
{% endblock content %}